cask_args appdir: "#{Dir.home}/Applications"

# private tools
cask "balenaetcher"
cask "brave-browser"
cask "chatgpt"
cask "codex"
cask "google-chrome"
brew "mariadb-connector-c"
cask "multipass"
brew "podman"
cask "steam"
cask "vlc"
